pub enum KafkaError {
    UnknownServerError,
    None,
    OffsetOutOfRange,
    CorruptMessage,
    UnknownTopicOrPartition,
    InvalidFetchSize,
    LeaderNotAvailable,
    NotLeaderOrFollower,
    RequestTimedOut,
    BrokerNotAvailable,
    ReplicaNotAvailable,
    MessageTooLarge,
    StaleControllerEpoch,
    OffsetMetadataTooLarge,
    NetworkException,
    CoordinatorLoadInProgress,
    CoordinatorNotAvailable,
    NotCoordinator,
    InvalidTopicException,
    RecordListTooLarge,
    NotEnoughReplicas,
    NotEnoughReplicasAfterAppend,
    InvalidRequiredAcks,
    IllegalGeneration,
    InconsistentGroupProtocol,
    InvalidGroupId,
    UnknownMemberId,
    InvalidSessionTimeout,
    RebalanceInProgress,
    InvalidCommitOffsetSize,
    TopicAuthorizationFailed,
    GroupAuthorizationFailed,
    ClusterAuthorizationFailed,
    InvalidTimestamp,
    UnsupportedSaslMechanism,
    IllegalSaslState,
    UnsupportedVersion,
    TopicAlreadyExists,
    InvalidPartitions,
    InvalidReplicationFactor,
    InvalidReplicaAssignment,
    InvalidConfig,
    NotController,
    InvalidRequest,
    UnsupportedForMessageFormat,
    PolicyViolation,
    OutOfOrderSequenceNumber,
    DuplicateSequenceNumber,
    InvalidProducerEpoch,
    InvalidTxnState,
    InvalidProducerIdMapping,
    InvalidTransactionTimeout,
    ConcurrentTransactions,
    TransactionCoordinatorFenced,
    TransactionalIdAuthorizationFailed,
    SecurityDisabled,
    OperationNotAttempted,
    KafkaStorageError,
    LogDirNotFound,
    SaslAuthenticationFailed,
    UnknownProducerId,
    ReassignmentInProgress,
    DelegationTokenAuthDisabled,
    DelegationTokenNotFound,
    DelegationTokenOwnerMismatch,
    DelegationTokenRequestNotAllowed,
    DelegationTokenAuthorizationFailed,
    DelegationTokenExpired,
    InvalidPrincipalType,
    NonEmptyGroup,
    GroupIdNotFound,
    FetchSessionIdNotFound,
    InvalidFetchSessionEpoch,
    ListenerNotFound,
    TopicDeletionDisabled,
    FencedLeaderEpoch,
    UnknownLeaderEpoch,
    UnsupportedCompressionType,
    StaleBrokerEpoch,
    OffsetNotAvailable,
    MemberIdRequired,
    PreferredLeaderNotAvailable,
    GroupMaxSizeReached,
    FencedInstanceId,
    EligibleLeadersNotAvailable,
    ElectionNotNeeded,
    NoReassignmentInProgress,
    GroupSubscribedToTopic,
    InvalidRecord,
    UnstableOffsetCommit,
    ThrottlingQuotaExceeded,
    ProducerFenced,
    ResourceNotFound,
    DuplicateResource,
    UnacceptableCredential,
    InconsistentVoterSet,
    InvalidUpdateVersion,
    FeatureUpdateFailed,
    PrincipalDeserializationFailure,
    SnapshotNotFound,
    PositionOutOfRange,
    UnknownTopicId,
    DuplicateBrokerRegistration,
    BrokerIdNotRegistered,
    InconsistentTopicId,
    InconsistentClusterId,
    TransactionalIdNotFound,
    FetchSessionTopicIdError,
    IneligibleReplica,
    NewLeaderElected,
    OffsetMovedToTieredStorage,
    FencedMemberEpoch,
    UnreleasedInstanceId,
    UnsupportedAssignor,
    StaleMemberEpoch,
    MismatchedEndpointType,
    UnsupportedEndpointType,
    UnknownControllerId,
    UnknownSubscriptionId,
    TelemetryTooLarge,
    InvalidRegistration,
    TransactionAbortable,
    InvalidRecordState,
    ShareSessionNotFound,
    InvalidShareSessionEpoch,
    FencedStateEpoch,
    InvalidVoterKey,
    DuplicateVoter,
    VoterNotFound,
    InvalidRegularExpression,
    RebootstrapRequired,
}

impl From<i16> for KafkaError {
    fn from(value: i16) -> Self {
        match value {
            0 => KafkaError::None,
            1 => KafkaError::OffsetOutOfRange,
            2 => KafkaError::CorruptMessage,
            3 => KafkaError::UnknownTopicOrPartition,
            4 => KafkaError::InvalidFetchSize,
            5 => KafkaError::LeaderNotAvailable,
            6 => KafkaError::NotLeaderOrFollower,
            7 => KafkaError::RequestTimedOut,
            8 => KafkaError::BrokerNotAvailable,
            9 => KafkaError::ReplicaNotAvailable,
            10 => KafkaError::MessageTooLarge,
            11 => KafkaError::StaleControllerEpoch,
            12 => KafkaError::OffsetMetadataTooLarge,
            13 => KafkaError::NetworkException,
            14 => KafkaError::CoordinatorLoadInProgress,
            15 => KafkaError::CoordinatorNotAvailable,
            16 => KafkaError::NotCoordinator,
            17 => KafkaError::InvalidTopicException,
            18 => KafkaError::RecordListTooLarge,
            19 => KafkaError::NotEnoughReplicas,
            20 => KafkaError::NotEnoughReplicasAfterAppend,
            21 => KafkaError::InvalidRequiredAcks,
            22 => KafkaError::IllegalGeneration,
            23 => KafkaError::InconsistentGroupProtocol,
            24 => KafkaError::InvalidGroupId,
            25 => KafkaError::UnknownMemberId,
            26 => KafkaError::InvalidSessionTimeout,
            27 => KafkaError::RebalanceInProgress,
            28 => KafkaError::InvalidCommitOffsetSize,
            29 => KafkaError::TopicAuthorizationFailed,
            30 => KafkaError::GroupAuthorizationFailed,
            31 => KafkaError::ClusterAuthorizationFailed,
            32 => KafkaError::InvalidTimestamp,
            33 => KafkaError::UnsupportedSaslMechanism,
            34 => KafkaError::IllegalSaslState,
            35 => KafkaError::UnsupportedVersion,
            36 => KafkaError::TopicAlreadyExists,
            37 => KafkaError::InvalidPartitions,
            38 => KafkaError::InvalidReplicationFactor,
            39 => KafkaError::InvalidReplicaAssignment,
            40 => KafkaError::InvalidConfig,
            41 => KafkaError::NotController,
            42 => KafkaError::InvalidRequest,
            43 => KafkaError::UnsupportedForMessageFormat,
            44 => KafkaError::PolicyViolation,
            45 => KafkaError::OutOfOrderSequenceNumber,
            46 => KafkaError::DuplicateSequenceNumber,
            47 => KafkaError::InvalidProducerEpoch,
            48 => KafkaError::InvalidTxnState,
            49 => KafkaError::InvalidProducerIdMapping,
            50 => KafkaError::InvalidTransactionTimeout,
            51 => KafkaError::ConcurrentTransactions,
            52 => KafkaError::TransactionCoordinatorFenced,
            53 => KafkaError::TransactionalIdAuthorizationFailed,
            54 => KafkaError::SecurityDisabled,
            55 => KafkaError::OperationNotAttempted,
            56 => KafkaError::KafkaStorageError,
            57 => KafkaError::LogDirNotFound,
            58 => KafkaError::SaslAuthenticationFailed,
            59 => KafkaError::UnknownProducerId,
            60 => KafkaError::ReassignmentInProgress,
            61 => KafkaError::DelegationTokenAuthDisabled,
            62 => KafkaError::DelegationTokenNotFound,
            63 => KafkaError::DelegationTokenOwnerMismatch,
            64 => KafkaError::DelegationTokenRequestNotAllowed,
            65 => KafkaError::DelegationTokenAuthorizationFailed,
            66 => KafkaError::DelegationTokenExpired,
            67 => KafkaError::InvalidPrincipalType,
            68 => KafkaError::NonEmptyGroup,
            69 => KafkaError::GroupIdNotFound,
            70 => KafkaError::FetchSessionIdNotFound,
            71 => KafkaError::InvalidFetchSessionEpoch,
            72 => KafkaError::ListenerNotFound,
            73 => KafkaError::TopicDeletionDisabled,
            74 => KafkaError::FencedLeaderEpoch,
            75 => KafkaError::UnknownLeaderEpoch,
            76 => KafkaError::UnsupportedCompressionType,
            77 => KafkaError::StaleBrokerEpoch,
            78 => KafkaError::OffsetNotAvailable,
            79 => KafkaError::MemberIdRequired,
            80 => KafkaError::PreferredLeaderNotAvailable,
            81 => KafkaError::GroupMaxSizeReached,
            82 => KafkaError::FencedInstanceId,
            83 => KafkaError::EligibleLeadersNotAvailable,
            84 => KafkaError::ElectionNotNeeded,
            85 => KafkaError::NoReassignmentInProgress,
            86 => KafkaError::GroupSubscribedToTopic,
            87 => KafkaError::InvalidRecord,
            88 => KafkaError::UnstableOffsetCommit,
            89 => KafkaError::ThrottlingQuotaExceeded,
            90 => KafkaError::ProducerFenced,
            91 => KafkaError::ResourceNotFound,
            92 => KafkaError::DuplicateResource,
            93 => KafkaError::UnacceptableCredential,
            94 => KafkaError::InconsistentVoterSet,
            95 => KafkaError::InvalidUpdateVersion,
            96 => KafkaError::FeatureUpdateFailed,
            97 => KafkaError::PrincipalDeserializationFailure,
            98 => KafkaError::SnapshotNotFound,
            99 => KafkaError::PositionOutOfRange,
            100 => KafkaError::UnknownTopicId,
            101 => KafkaError::DuplicateBrokerRegistration,
            102 => KafkaError::BrokerIdNotRegistered,
            103 => KafkaError::InconsistentTopicId,
            104 => KafkaError::InconsistentClusterId,
            105 => KafkaError::TransactionalIdNotFound,
            106 => KafkaError::FetchSessionTopicIdError,
            107 => KafkaError::IneligibleReplica,
            108 => KafkaError::NewLeaderElected,
            109 => KafkaError::OffsetMovedToTieredStorage,
            110 => KafkaError::FencedMemberEpoch,
            111 => KafkaError::UnreleasedInstanceId,
            112 => KafkaError::UnsupportedAssignor,
            113 => KafkaError::StaleMemberEpoch,
            114 => KafkaError::MismatchedEndpointType,
            115 => KafkaError::UnsupportedEndpointType,
            116 => KafkaError::UnknownControllerId,
            117 => KafkaError::UnknownSubscriptionId,
            118 => KafkaError::TelemetryTooLarge,
            119 => KafkaError::InvalidRegistration,
            120 => KafkaError::TransactionAbortable,
            121 => KafkaError::InvalidRecordState,
            122 => KafkaError::ShareSessionNotFound,
            123 => KafkaError::InvalidShareSessionEpoch,
            124 => KafkaError::FencedStateEpoch,
            125 => KafkaError::InvalidVoterKey,
            126 => KafkaError::DuplicateVoter,
            127 => KafkaError::VoterNotFound,
            128 => KafkaError::InvalidRegularExpression,
            129 => KafkaError::RebootstrapRequired,
            _ => KafkaError::UnknownServerError,
        }
    }
}

impl Into<i16> for KafkaError {
    fn into(self) -> i16 {
        match self {
            KafkaError::None => 0,
            KafkaError::OffsetOutOfRange => 1,
            KafkaError::CorruptMessage => 2,
            KafkaError::UnknownTopicOrPartition => 3,
            KafkaError::InvalidFetchSize => 4,
            KafkaError::LeaderNotAvailable => 5,
            KafkaError::NotLeaderOrFollower => 6,
            KafkaError::RequestTimedOut => 7,
            KafkaError::BrokerNotAvailable => 8,
            KafkaError::ReplicaNotAvailable => 9,
            KafkaError::MessageTooLarge => 10,
            KafkaError::StaleControllerEpoch => 11,
            KafkaError::OffsetMetadataTooLarge => 12,
            KafkaError::NetworkException => 13,
            KafkaError::CoordinatorLoadInProgress => 14,
            KafkaError::CoordinatorNotAvailable => 15,
            KafkaError::NotCoordinator => 16,
            KafkaError::InvalidTopicException => 17,
            KafkaError::RecordListTooLarge => 18,
            KafkaError::NotEnoughReplicas => 19,
            KafkaError::NotEnoughReplicasAfterAppend => 20,
            KafkaError::InvalidRequiredAcks => 21,
            KafkaError::IllegalGeneration => 22,
            KafkaError::InconsistentGroupProtocol => 23,
            KafkaError::InvalidGroupId => 24,
            KafkaError::UnknownMemberId => 25,
            KafkaError::InvalidSessionTimeout => 26,
            KafkaError::RebalanceInProgress => 27,
            KafkaError::InvalidCommitOffsetSize => 28,
            KafkaError::TopicAuthorizationFailed => 29,
            KafkaError::GroupAuthorizationFailed => 30,
            KafkaError::ClusterAuthorizationFailed => 31,
            KafkaError::InvalidTimestamp => 32,
            KafkaError::UnsupportedSaslMechanism => 33,
            KafkaError::IllegalSaslState => 34,
            KafkaError::UnsupportedVersion => 35,
            KafkaError::TopicAlreadyExists => 36,
            KafkaError::InvalidPartitions => 37,
            KafkaError::InvalidReplicationFactor => 38,
            KafkaError::InvalidReplicaAssignment => 39,
            KafkaError::InvalidConfig => 40,
            KafkaError::NotController => 41,
            KafkaError::InvalidRequest => 42,
            KafkaError::UnsupportedForMessageFormat => 43,
            KafkaError::PolicyViolation => 44,
            KafkaError::OutOfOrderSequenceNumber => 45,
            KafkaError::DuplicateSequenceNumber => 46,
            KafkaError::InvalidProducerEpoch => 47,
            KafkaError::InvalidTxnState => 48,
            KafkaError::InvalidProducerIdMapping => 49,
            KafkaError::InvalidTransactionTimeout => 50,
            KafkaError::ConcurrentTransactions => 51,
            KafkaError::TransactionCoordinatorFenced => 52,
            KafkaError::TransactionalIdAuthorizationFailed => 53,
            KafkaError::SecurityDisabled => 54,
            KafkaError::OperationNotAttempted => 55,
            KafkaError::KafkaStorageError => 56,
            KafkaError::LogDirNotFound => 57,
            KafkaError::SaslAuthenticationFailed => 58,
            KafkaError::UnknownProducerId => 59,
            KafkaError::ReassignmentInProgress => 60,
            KafkaError::DelegationTokenAuthDisabled => 61,
            KafkaError::DelegationTokenNotFound => 62,
            KafkaError::DelegationTokenOwnerMismatch => 63,
            KafkaError::DelegationTokenRequestNotAllowed => 64,
            KafkaError::DelegationTokenAuthorizationFailed => 65,
            KafkaError::DelegationTokenExpired => 66,
            KafkaError::InvalidPrincipalType => 67,
            KafkaError::NonEmptyGroup => 68,
            KafkaError::GroupIdNotFound => 69,
            KafkaError::FetchSessionIdNotFound => 70,
            KafkaError::InvalidFetchSessionEpoch => 71,
            KafkaError::ListenerNotFound => 72,
            KafkaError::TopicDeletionDisabled => 73,
            KafkaError::FencedLeaderEpoch => 74,
            KafkaError::UnknownLeaderEpoch => 75,
            KafkaError::UnsupportedCompressionType => 76,
            KafkaError::StaleBrokerEpoch => 77,
            KafkaError::OffsetNotAvailable => 78,
            KafkaError::MemberIdRequired => 79,
            KafkaError::PreferredLeaderNotAvailable => 80,
            KafkaError::GroupMaxSizeReached => 81,
            KafkaError::FencedInstanceId => 82,
            KafkaError::EligibleLeadersNotAvailable => 83,
            KafkaError::ElectionNotNeeded => 84,
            KafkaError::NoReassignmentInProgress => 85,
            KafkaError::GroupSubscribedToTopic => 86,
            KafkaError::InvalidRecord => 87,
            KafkaError::UnstableOffsetCommit => 88,
            KafkaError::ThrottlingQuotaExceeded => 89,
            KafkaError::ProducerFenced => 90,
            KafkaError::ResourceNotFound => 91,
            KafkaError::DuplicateResource => 92,
            KafkaError::UnacceptableCredential => 93,
            KafkaError::InconsistentVoterSet => 94,
            KafkaError::InvalidUpdateVersion => 95,
            KafkaError::FeatureUpdateFailed => 96,
            KafkaError::PrincipalDeserializationFailure => 97,
            KafkaError::SnapshotNotFound => 98,
            KafkaError::PositionOutOfRange => 99,
            KafkaError::UnknownTopicId => 100,
            KafkaError::DuplicateBrokerRegistration => 101,
            KafkaError::BrokerIdNotRegistered => 102,
            KafkaError::InconsistentTopicId => 103,
            KafkaError::InconsistentClusterId => 104,
            KafkaError::TransactionalIdNotFound => 105,
            KafkaError::FetchSessionTopicIdError => 106,
            KafkaError::IneligibleReplica => 107,
            KafkaError::NewLeaderElected => 108,
            KafkaError::OffsetMovedToTieredStorage => 109,
            KafkaError::FencedMemberEpoch => 110,
            KafkaError::UnreleasedInstanceId => 111,
            KafkaError::UnsupportedAssignor => 112,
            KafkaError::StaleMemberEpoch => 113,
            KafkaError::MismatchedEndpointType => 114,
            KafkaError::UnsupportedEndpointType => 115,
            KafkaError::UnknownControllerId => 116,
            KafkaError::UnknownSubscriptionId => 117,
            KafkaError::TelemetryTooLarge => 118,
            KafkaError::InvalidRegistration => 119,
            KafkaError::TransactionAbortable => 120,
            KafkaError::InvalidRecordState => 121,
            KafkaError::ShareSessionNotFound => 122,
            KafkaError::InvalidShareSessionEpoch => 123,
            KafkaError::FencedStateEpoch => 124,
            KafkaError::InvalidVoterKey => 125,
            KafkaError::DuplicateVoter => 126,
            KafkaError::VoterNotFound => 127,
            KafkaError::InvalidRegularExpression => 128,
            KafkaError::RebootstrapRequired => 129,
            KafkaError::UnknownServerError => -1,
        }
    }
}
