#[derive(Debug)]
pub enum RequestApi {
    Invalid,
    Produce,
    Fetch,
    ListOffsets,
    Metadata,
    OffsetCommit,
    OffsetFetch,
    FindCoordinator,
    JoinGroup,
    Heartbeat,
    LeaveGroup,
    SyncGroup,
    DescribeGroups,
    ListGroups,
    SaslHandshake,
    ApiVersions,
    CreateTopics,
    DeleteTopics,
    DeleteRecords,
    InitProducerId,
    OffsetForLeaderEpoch,
    AddPartitionsToTxn,
    AddOffsetsToTxn,
    EndTxn,
    WriteTxnMarkers,
    TxnOffsetCommit,
    DescribeAcls,
    CreateAcls,
    DeleteAcls,
    DescribeConfigs,
    AlterConfigs,
    AlterReplicaLogDirs,
    DescribeLogDirs,
    SaslAuthenticate,
    CreatePartitions,
    CreateDelegationToken,
    RenewDelegationToken,
    ExpireDelegationToken,
    DescribeDelegationToken,
    DeleteGroups,
    ElectLeaders,
    IncrementalAlterConfigs,
    AlterPartitionReassignments,
    ListPartitionReassignments,
    OffsetDelete,
    DescribeClientQuotas,
    AlterClientQuotas,
    DescribeUserScramCredentials,
    AlterUserScramCredentials,
    DescribeQuorum,
    UpdateFeatures,
    DescribeCluster,
    DescribeProducers,
    UnregisterBroker,
    DescribeTransactions,
    ListTransactions,
    ConsumerGroupHeartbeat,
    ConsumerGroupDescribe,
    GetTelemetrySubscriptions,
    PushTelemetry,
    ListClientMetricsResources,
    DescribeTopicPartitions,
    AddRaftVoter,
    RemoveRaftVoter,
}
impl From<i16> for RequestApi {
    fn from(value: i16) -> Self {
        match value {
            0 => RequestApi::Produce,
            1 => RequestApi::Fetch,
            2 => RequestApi::ListOffsets,
            3 => RequestApi::Metadata,
            8 => RequestApi::OffsetCommit,
            9 => RequestApi::OffsetFetch,
            10 => RequestApi::FindCoordinator,
            11 => RequestApi::JoinGroup,
            12 => RequestApi::Heartbeat,
            13 => RequestApi::LeaveGroup,
            14 => RequestApi::SyncGroup,
            15 => RequestApi::DescribeGroups,
            16 => RequestApi::ListGroups,
            17 => RequestApi::SaslHandshake,
            18 => RequestApi::ApiVersions,
            19 => RequestApi::CreateTopics,
            20 => RequestApi::DeleteTopics,
            21 => RequestApi::DeleteRecords,
            22 => RequestApi::InitProducerId,
            23 => RequestApi::OffsetForLeaderEpoch,
            24 => RequestApi::AddPartitionsToTxn,
            25 => RequestApi::AddOffsetsToTxn,
            26 => RequestApi::EndTxn,
            27 => RequestApi::WriteTxnMarkers,
            28 => RequestApi::TxnOffsetCommit,
            29 => RequestApi::DescribeAcls,
            30 => RequestApi::CreateAcls,
            31 => RequestApi::DeleteAcls,
            32 => RequestApi::DescribeConfigs,
            33 => RequestApi::AlterConfigs,
            34 => RequestApi::AlterReplicaLogDirs,
            35 => RequestApi::DescribeLogDirs,
            36 => RequestApi::SaslAuthenticate,
            37 => RequestApi::CreatePartitions,
            38 => RequestApi::CreateDelegationToken,
            39 => RequestApi::RenewDelegationToken,
            40 => RequestApi::ExpireDelegationToken,
            41 => RequestApi::DescribeDelegationToken,
            42 => RequestApi::DeleteGroups,
            43 => RequestApi::ElectLeaders,
            44 => RequestApi::IncrementalAlterConfigs,
            45 => RequestApi::AlterPartitionReassignments,
            46 => RequestApi::ListPartitionReassignments,
            47 => RequestApi::OffsetDelete,
            48 => RequestApi::DescribeClientQuotas,
            49 => RequestApi::AlterClientQuotas,
            50 => RequestApi::DescribeUserScramCredentials,
            51 => RequestApi::AlterUserScramCredentials,
            55 => RequestApi::DescribeQuorum,
            57 => RequestApi::UpdateFeatures,
            60 => RequestApi::DescribeCluster,
            61 => RequestApi::DescribeProducers,
            64 => RequestApi::UnregisterBroker,
            65 => RequestApi::DescribeTransactions,
            66 => RequestApi::ListTransactions,
            68 => RequestApi::ConsumerGroupHeartbeat,
            69 => RequestApi::ConsumerGroupDescribe,
            71 => RequestApi::GetTelemetrySubscriptions,
            72 => RequestApi::PushTelemetry,
            74 => RequestApi::ListClientMetricsResources,
            75 => RequestApi::DescribeTopicPartitions,
            80 => RequestApi::AddRaftVoter,
            82 => RequestApi::RemoveRaftVoter,
            _ => RequestApi::Invalid,
        }
    }
}

impl Into<i16> for RequestApi {
    fn into(self) -> i16 {
        match self {
            RequestApi::Invalid => -1,
            RequestApi::Produce => 0,
            RequestApi::Fetch => 1,
            RequestApi::ListOffsets => 2,
            RequestApi::Metadata => 3,
            RequestApi::OffsetCommit => 8,
            RequestApi::OffsetFetch => 9,
            RequestApi::FindCoordinator => 10,
            RequestApi::JoinGroup => 11,
            RequestApi::Heartbeat => 12,
            RequestApi::LeaveGroup => 13,
            RequestApi::SyncGroup => 14,
            RequestApi::DescribeGroups => 15,
            RequestApi::ListGroups => 16,
            RequestApi::SaslHandshake => 17,
            RequestApi::ApiVersions => 18,
            RequestApi::CreateTopics => 19,
            RequestApi::DeleteTopics => 20,
            RequestApi::DeleteRecords => 21,
            RequestApi::InitProducerId => 22,
            RequestApi::OffsetForLeaderEpoch => 23,
            RequestApi::AddPartitionsToTxn => 24,
            RequestApi::AddOffsetsToTxn => 25,
            RequestApi::EndTxn => 26,
            RequestApi::WriteTxnMarkers => 27,
            RequestApi::TxnOffsetCommit => 28,
            RequestApi::DescribeAcls => 29,
            RequestApi::CreateAcls => 30,
            RequestApi::DeleteAcls => 31,
            RequestApi::DescribeConfigs => 32,
            RequestApi::AlterConfigs => 33,
            RequestApi::AlterReplicaLogDirs => 34,
            RequestApi::DescribeLogDirs => 35,
            RequestApi::SaslAuthenticate => 36,
            RequestApi::CreatePartitions => 37,
            RequestApi::CreateDelegationToken => 38,
            RequestApi::RenewDelegationToken => 39,
            RequestApi::ExpireDelegationToken => 40,
            RequestApi::DescribeDelegationToken => 41,
            RequestApi::DeleteGroups => 42,
            RequestApi::ElectLeaders => 43,
            RequestApi::IncrementalAlterConfigs => 44,
            RequestApi::AlterPartitionReassignments => 45,
            RequestApi::ListPartitionReassignments => 46,
            RequestApi::OffsetDelete => 47,
            RequestApi::DescribeClientQuotas => 48,
            RequestApi::AlterClientQuotas => 49,
            RequestApi::DescribeUserScramCredentials => 50,
            RequestApi::AlterUserScramCredentials => 51,
            RequestApi::DescribeQuorum => 55,
            RequestApi::UpdateFeatures => 57,
            RequestApi::DescribeCluster => 60,
            RequestApi::DescribeProducers => 61,
            RequestApi::UnregisterBroker => 64,
            RequestApi::DescribeTransactions => 65,
            RequestApi::ListTransactions => 66,
            RequestApi::ConsumerGroupHeartbeat => 68,
            RequestApi::ConsumerGroupDescribe => 69,
            RequestApi::GetTelemetrySubscriptions => 71,
            RequestApi::PushTelemetry => 72,
            RequestApi::ListClientMetricsResources => 74,
            RequestApi::DescribeTopicPartitions => 75,
            RequestApi::AddRaftVoter => 80,
            RequestApi::RemoveRaftVoter => 81,
        }
    }
}
